global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  # Scrape the pushgateway (batches/Ansible push here)
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']
